# Generated by Django 5.2.4 on 2026-03-31 10:43

import Models.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('person_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('dob', models.DateField(db_column='DOB')),
                ('cnic', models.CharField(db_column='CNIC', max_length=15, unique=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('institutional_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('Admin', 'Admin'), ('Faculty', 'Faculty'), ('Student', 'Student')], db_column='type', max_length=7)),
                ('user', models.OneToOneField(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'person',
                'ordering': ['person_id', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Project', 'Project'), ('Presentation', 'Presentation'), ('Mid Exam', 'Mid Exam'), ('Final Exam', 'Final Exam'), ('Lab', 'Lab')], max_length=15)),
                ('assessment_name', models.CharField(max_length=20)),
                ('weightage', models.IntegerField()),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('total_marks', models.IntegerField()),
                ('student_submission', models.BooleanField(default=False)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessment',
                'ordering': ['assessment_id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_inauguration_date', models.DateField(blank=True, db_column='establishmentDate', null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], db_index=True, default='Inactive', max_length=15)),
                ('session', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('activation_deadline', models.DateTimeField(blank=True, null=True)),
                ('closing_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'semester',
                'ordering': ['semester_id', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Models.person')),
                ('country', models.CharField(blank=True, max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=50)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='Models.person')),
                ('joining_date', models.DateField(blank=True, default=Models.models.current_time)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Acting', 'Acting')], default='Active', max_length=10)),
            ],
            options={
                'db_table': 'Admin',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Models.models.assessment_upload_path)),
                ('file_name', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=10)),
                ('entity_name', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(db_index=True, default=Models.models.current_time)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.CharField(max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.person')),
            ],
            options={
                'db_table': 'auditTrail',
                'ordering': ['-time_stamp'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_index=True, max_length=100)),
                ('credit_hours', models.PositiveIntegerField(default=0)),
                ('lab', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('pre_requisite', models.ForeignKey(blank=True, db_column='preRequisite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Models.course')),
            ],
            options={
                'db_table': 'course',
                'ordering': ['course_code', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='status', default='Inactive', max_length=9)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.semester')),
            ],
            options={
                'db_table': 'courseAllocation',
                'ordering': ['allocation_id', 'faculty', 'semester'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.courseallocation'),
        ),
        migrations.CreateModel(
            name='AllocationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Models.models.course_allocation_upload_path)),
                ('file_name', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.courseallocation')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lecture_no', models.PositiveIntegerField()),
                ('venue', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_time', models.DateTimeField(db_column='startingTime')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.courseallocation')),
            ],
            options={
                'db_table': 'lecture',
                'ordering': ['starting_time'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('program_name', models.CharField(db_index=True, max_length=100)),
                ('total_semesters', models.IntegerField(blank=True, default=8)),
                ('fee_per_semester', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Models.department')),
            ],
            options={
                'db_table': 'program',
                'ordering': ['program_id'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_year', models.IntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.program')),
            ],
            options={
                'db_table': 'class',
                'ordering': ['batch_year'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_title', models.CharField(max_length=50)),
                ('education_board', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.CharField(max_length=50)),
                ('passing_year', models.TextField(blank=True, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.person')),
            ],
            options={
                'db_table': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='Models.person')),
                ('designation', models.CharField(choices=[('Lab Engineer', 'Lab Engineer'), ('Lecturer', 'Lecturer'), ('Senior Lecturer', 'Senior Lecturer'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], db_index=True, max_length=20)),
                ('joining_date', models.DateField(blank=True, default=Models.models.current_time)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.department')),
            ],
            options={
                'db_table': 'Faculty',
                'ordering': ['employee_id', 'department', 'designation'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='HOD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hod', to='Models.faculty'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.faculty'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='Models.person')),
                ('admission_date', models.DateField(blank=True, default=Models.models.current_time)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dropped', 'Dropped'), ('Frozen', 'Frozen'), ('Graduated', 'Graduated'), ('On Probation', 'On Probation')], db_column='status', db_index=True, default='Active', max_length=12)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.program')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.class')),
            ],
            options={
                'db_table': 'Student',
                'ordering': ['student_id', 'student_class', 'admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(default=Models.models.current_time)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], db_index=True, default='Inactive', max_length=9)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.courseallocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.student')),
            ],
            options={
                'db_table': 'enrollment',
                'ordering': ['enrollment_id', 'student', 'allocation'],
                'unique_together': {('student', 'allocation')},
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('hod_change', 'HOD Change'), ('faculty_delete', 'Faculty Delete'), ('student_delete', 'Student Delete'), ('result_calculation', 'Result Calculation')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('applied', 'Applied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.courseallocation')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.department')),
                ('new_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_change_requests', to='Models.faculty')),
                ('target_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='Models.faculty')),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='Models.student')),
            ],
            options={
                'db_table': 'change_request',
            },
        ),
        migrations.CreateModel(
            name='AssessmentChecked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('student_upload', models.FileField(blank=True, null=True, upload_to=Models.models.assessment_checked_upload_path)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.enrollment')),
            ],
            options={
                'db_table': 'assessmentChecked',
                'unique_together': {('assessment', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.enrollment')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.lecture')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('attendance_date', 'enrollment', 'lecture')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Models.enrollment')),
            ],
            options={
                'db_table': 'result',
                'constraints': [models.CheckConstraint(condition=models.Q(('obtained_marks__gte', 0), ('obtained_marks__lte', 100)), name='valid_obtained_marks_range'), models.CheckConstraint(condition=models.Q(('course_gpa__gte', 0.0), ('course_gpa__lte', 4.0)), name='valid_course_gpa_range')],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('create_date', models.DateTimeField(db_column='createdAt', default=Models.models.current_time)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.enrollment')),
            ],
            options={
                'db_table': 'reviews',
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 0.0), ('rating__lte', 10.0)), name='rating_range')],
            },
        ),
        migrations.CreateModel(
            name='SemesterDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.semester')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.class')),
            ],
            options={
                'db_table': 'semesterDetails',
                'ordering': ['id'],
                'unique_together': {('course', 'student_class', 'semester')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('faculty', 'course', 'semester')},
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_credits', models.IntegerField()),
                ('semester_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.student')),
            ],
            options={
                'db_table': 'transcript',
                'constraints': [models.CheckConstraint(condition=models.Q(('semester_gpa__gte', 0.0), ('semester_gpa__lte', 4.0)), name='semester_gpa_range')],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
