# Generated by Django 5.2.4 on 2025-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
