# Generated by Django 5.2.4 on 2026-03-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='create_date',
        ),
    ]
