# Generated by Django 5.2.4 on 2026-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_remove_reviews_create_date_reviews_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', default='2026-01-01 00:00:00+00:00'),
            preserve_default=False,
        ),
    ]
