# Generated by Django 5.2.4 on 2026-03-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_reviews_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
