# Generated by Django 5.2.4 on 2026-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_alter_audittrail_time_stamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=10)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Initiated', 'Initiated'), ('Available', 'Available'), ('Active', 'Active'), ('Completed', 'Completed')], db_index=True, default='Inactive', max_length=15)),
                ('activation_deadline', models.DateTimeField(blank=True, null=True)),
                ('availability_delta', models.PositiveIntegerField(default=7)),
                ('closing_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year', 'period'],
                'unique_together': {('period', 'year')},
            },
        ),
    ]
