# Generated by Django 5.2.4 on 2026-08-15 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_academicsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='associated_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Models.class'),
        ),
    ]
