# Generated by Django 5.2.4 on 2026-08-15 10:05

from django.db import migrations


def backfill_associated_class(apps, schema_editor):
    Semester = apps.get_model('Models', 'Semester')
    SemesterDetails = apps.get_model('Models', 'SemesterDetails')
    for semester in Semester.objects.filter(associated_class__isnull=True):
        class_id = SemesterDetails.objects.filter(semester=semester).values_list('student_class', flat=True).first()
        if class_id:
            semester.associated_class_id = class_id
            semester.save(update_fields=['associated_class'])


def unset_associated_class(apps, schema_editor):
    Semester = apps.get_model('Models', 'Semester')
    Semester.objects.update(associated_class=None)


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_semester_associated_class'),
    ]

    operations = [
        migrations.RunPython(backfill_associated_class, unset_associated_class),
    ]
