# Generated by Django 5.2.4 on 2025-08-07 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_remove_result_valid_obtained_marks_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
