# Generated by Django 5.2.4 on 2026-08-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_backfill_semester_associated_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semesterdetails',
            unique_together={('course', 'semester')},
        ),
        migrations.AlterField(
            model_name='semester',
            name='associated_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.class'),
        ),
        migrations.RemoveField(
            model_name='semesterdetails',
            name='student_class',
        ),
    ]
