# Generated by Django 5.2.4 on 2026-08-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0008_alter_semesterdetails_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseallocation',
            name='session',
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='session_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Models.academicsession'),
        ),
        migrations.AddField(
            model_name='semester',
            name='session_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Models.academicsession'),
        ),
    ]
