# Generated by Django 5.2.4 on 2026-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0009_remove_courseallocation_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseallocation',
            name='session_period',
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='session',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
