# Generated by Django 5.2.4 on 2025-08-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0010_alter_department_hod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='officeLocation',
            new_name='office_location',
        ),
    ]
