# Generated by Django 5.2.4 on 2026-08-15 12:25

from django.db import migrations


def backfill_session_period(apps, schema_editor):
    Semester = apps.get_model('Models', 'Semester')
    AcademicSession = apps.get_model('Models', 'AcademicSession')

    valid_periods = {'Fall', 'Spring'}

    for semester in Semester.objects.filter(session_period__isnull=True, session__isnull=False):
        raw = semester.session.strip()
        parts = raw.split('-')
        if len(parts) != 2:
            continue
        period, year_str = parts[0].strip(), parts[1].strip()
        if period not in valid_periods or not year_str.isdigit():
            continue

        academic_session, _ = AcademicSession.objects.get_or_create(
            period=period, year=int(year_str),
        )
        semester.session_period = academic_session
        semester.save(update_fields=['session_period'])


def unset_session_period(apps, schema_editor):
    Semester = apps.get_model('Models', 'Semester')
    Semester.objects.update(session_period=None)


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0010_remove_courseallocation_session_period_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_session_period, unset_session_period),
    ]
