# Generated by Django 5.2.4 on 2026-08-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_backfill_semester_session_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='session',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='session_period',
            new_name='session',
        ),
    ]
