# Generated by Django 5.2.4 on 2025-08-09 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0012_alter_student_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 9)),
        ),
    ]
