# Generated by Django 5.2.4 on 2025-08-10 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0013_alter_faculty_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 10)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 10)),
        ),
    ]
