# Generated by Django 5.2.4 on 2026-09-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0013_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='activation_deadline',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='closing_deadline',
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('course', 'semester')},
        ),
    ]
