# Generated by Django 5.2.4 on 2026-09-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0014_remove_semester_activation_deadline_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('associated_class', 'session')},
        ),
    ]
