# Generated by Django 5.2.4 on 2026-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0015_alter_semester_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseallocation',
            name='passing_threshold',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Ongoing', 'Ongoing'), ('Result Done', 'Result Done'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='status', default='Inactive', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='courseallocation',
            constraint=models.CheckConstraint(condition=models.Q(('passing_threshold__gte', 30), ('passing_threshold__lte', 50)), name='valid_passing_threshold_range'),
        ),
    ]
