# Generated by Django 5.2.4 on 2026-09-04 18:56

from django.db import migrations, models


def rename_allocation_statuses(apps, schema_editor):
    """'Ongoing' becomes 'Active' for uniformity with the other lifecycle
    models. 'Result Done' — introduced and superseded within the same
    development cycle — becomes 'Locked'."""
    CourseAllocation = apps.get_model('Models', 'CourseAllocation')
    CourseAllocation.objects.filter(status='Ongoing').update(status='Active')
    CourseAllocation.objects.filter(status='Result Done').update(status='Locked')


def restore_allocation_statuses(apps, schema_editor):
    CourseAllocation = apps.get_model('Models', 'CourseAllocation')
    CourseAllocation.objects.filter(status='Locked').update(status='Result Done')
    CourseAllocation.objects.filter(status='Active').update(status='Ongoing')


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0016_courseallocation_passing_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Locked', 'Locked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='status', default='Inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Locked', 'Locked'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], db_index=True, default='Inactive', max_length=9),
        ),
        migrations.RunPython(rename_allocation_statuses, restore_allocation_statuses),
    ]
