# Generated by Django 5.2.4 on 2025-08-16 13:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0016_remove_assessmentchecked_result_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 16)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 16)),
        ),
    ]
