# Generated by Django 5.2.4 on 2026-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0017_alter_courseallocation_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.CheckConstraint(condition=models.Q(('closing_deadline__gt', models.F('activation_deadline'))), name='closing_deadline_after_activation_deadline'),
        ),
    ]
