# Generated by Django 5.2.4 on 2026-09-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0019_academicsession_deadline_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='courseallocation',
            options={'ordering': ['allocation_id']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['enrollment_id']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['pk']},
        ),
    ]
