# Generated by Django 5.2.4 on 2025-08-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0019_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ('starting_time',)},
        ),
    ]
