# Generated by Django 5.2.4 on 2025-08-22 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0020_alter_lecture_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 22)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 22)),
        ),
    ]
