# Generated by Django 5.2.4 on 2025-08-26 10:48

import Models.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0021_alter_audittrail_new_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=Models.models.Assessment.assessment_upload_path),
        ),
        migrations.AddField(
            model_name='assessmentchecked',
            name='student_upload',
            field=models.FileField(blank=True, null=True, upload_to=Models.models.AssessmentChecked.assessment_checked_upload_path),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=Models.models.CourseAllocation.course_allocation_upload_path),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 26)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 26)),
        ),
    ]
