# Generated by Django 5.2.4 on 2025-08-27 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0022_assessment_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='student_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 27)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 27)),
        ),
    ]
