# Generated by Django 5.2.4 on 2025-08-27 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0023_assessment_student_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='target_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.courseallocation'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='change_type',
            field=models.CharField(choices=[('hod_change', 'HOD Change'), ('faculty_delete', 'Faculty Delete'), ('student_delete', 'Student Delete'), ('result_calculation', 'Result Calculation')], max_length=20),
        ),
    ]
