# Generated by Django 5.2.4 on 2025-09-01 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0024_changerequest_target_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='activation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 9, 1)),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 9, 1)),
        ),
    ]
