# Generated by Django 5.2.4 on 2025-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0025_semester_activation_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='closing_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
