# Generated by Django 5.2.4 on 2025-09-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0026_semester_closing_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='status', default='Inactive', max_length=9),
        ),
    ]
