# Generated by Django 5.2.4 on 2025-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0027_alter_courseallocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Inactive', max_length=9),
        ),
    ]
