# Generated by Django 5.2.4 on 2025-09-06 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0029_alter_faculty_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
