# Generated by Django 5.2.4 on 2025-09-06 14:50

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0030_alter_faculty_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(blank=True, default=timezone.now().date()),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, default=timezone.now().date()),
        ),
    ]
