# Generated by Django 5.2.4 on 2025-09-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0032_alter_faculty_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Project', 'Project'), ('Presentation', 'Presentation'), ('Mid Exam', 'Mid Exam'), ('Final Exam', 'Final Exam'), ('Lab', 'Lab')], max_length=15),
        ),
    ]
