# Generated by Django 5.2.4 on 2025-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0033_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
