# Generated by Django 5.2.4 on 2025-09-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0034_alter_department_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Models.department'),
        ),
    ]
