# Generated by Django 5.2.4 on 2025-09-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0035_alter_program_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Models.program'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='allocation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.courseallocation'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Models.student'),
        ),
    ]
