"""
Django settings for NexusAPI project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
import socket
from datetime import timedelta
from pathlib import Path
from decouple import config, Csv
import cloudinary

from rest_framework.permissions import DjangoModelPermissions

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # cloudinary_storage ships its own `collectstatic` that's a near-total
    # no-op unless STATICFILES_STORAGE is StaticCloudinaryStorage (it isn't —
    # WhiteNoise is). django.core.management.get_commands() resolves name
    # collisions by walking INSTALLED_APPS in reverse, so whichever app is
    # listed FIRST wins — keep staticfiles above cloudinary_storage so the
    # real collectstatic runs, not cloudinary's stub.
    'cloudinary_storage',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'cloudinary',
    'corsheaders',


    'Models',
    'AdminModule',
    'FacultyModule',
    'StudentModule',
    'NotificationModule',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'NexusAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NexusAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='LMS'),
        'USER': config('DB_USER', default='adminUser'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='database'),
        'PORT': config('DB_PORT', default='3306'),
    }
}


STORAGES = {
    'default': {
       'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Karachi'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise: serve static files from gunicorn/Django itself, so admin/DRF
# CSS still works even if nginx is down or misconfigured (as it always is
# in local dev, since nginx.conf is hardcoded for the production TLS certs).
WHITENOISE_USE_FINDERS = DEBUG

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Turns MySQL trigger rejections (SIGNAL 1644) into 400s instead of 500s.
    'EXCEPTION_HANDLER': 'NexusAPI.exception_handlers.api_exception_handler',

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('THROTTLE_ANON', default='30/minute'),
        'user': config('THROTTLE_USER', default='1000/minute'),
        'login': config('THROTTLE_LOGIN', default='20/minute'),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_MINUTES', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_DAYS', default=7, cast=int)),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}




# Redis Settings

REDIS_URL = config('REDIS_URL', default='redis://redis-server:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'TIMEOUT': 300,
        'KEY_PREFIX': 'LMS',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
            'CONNECTION_POOL_KWARGS': {'max_connections': 100, 'retry_on_timeout': True},
            'SOCKET_CONNECT_TIMEOUT': 2,
            'SOCKET_TIMEOUT': 2,
            'IGNORE_EXCEPTIONS': True,
        },
    },
    'pages': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL_PAGES', default=REDIS_URL),
        'TIMEOUT': 60,
        'KEY_PREFIX': 'lms:pages',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
        },
    },
}


# Test / benchmark isolation
# --------------------------
# Under pytest, point the database and cache at the dedicated containers
# (`docker compose --profile test up -d database-test redis-test`). Without
# this the suite shares MySQL and Redis with the running dev stack: the autouse
# `cache.clear()` fixtures flush whatever the app had cached, and benchmark
# timings compete with dev queries for the same buffer pool.

RUNNING_TESTS = (
    'PYTEST_CURRENT_TEST' in os.environ
    or 'pytest' in os.path.basename(sys.argv[0])
    # Lets a non-pytest process join the test stack -- the benchmark Celery
    # worker sets TEST_MODE=true so it reads database-test and redis-test.
    or config('TEST_MODE', default=False, cast=bool)
)

if RUNNING_TESTS:
    DATABASES['default']['HOST'] = config('TEST_DB_HOST', default='database-test')
    CACHES['default']['LOCATION'] = config(
        'TEST_REDIS_URL', default='redis://redis-test:6379/0'
    )
    CACHES['pages']['LOCATION'] = config(
        'TEST_REDIS_URL_PAGES', default='redis://redis-test:6379/1'
    )


# Celery Settings
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis-server:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://redis-server:6379/1')

if RUNNING_TESTS:
    # Keep benchmark jobs off the dev broker: a stray `.delay()` there would be
    # picked up by the live worker and run against the dev database. Databases
    # 2 and 3 so the broker does not collide with the test caches on 0 and 1.
    CELERY_BROKER_URL = config('TEST_CELERY_BROKER_URL', default='redis://redis-test:6379/2')
    CELERY_RESULT_BACKEND = config('TEST_CELERY_RESULT_BACKEND', default='redis://redis-test:6379/3')
    # Celery reads CELERY_BROKER_URL from the process environment itself, and
    # that autoset value beats config_from_object('django.conf:settings').
    # `.env` puts the dev broker there, so without this the settings above are
    # silently ignored and benchmark jobs land on the dev broker, where the
    # live worker would run them against the dev database.
    os.environ['CELERY_BROKER_URL'] = CELERY_BROKER_URL
    os.environ['CELERY_RESULT_BACKEND'] = CELERY_RESULT_BACKEND

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
CELERY_RESULT_EXPIRES = 3600
CELERY_WORKER_CONCURRENCY = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ALWAYS_EAGER = False
CELERY_WORKER_POOL = config('CELERY_WORKER_POOL', default='prefork')



# Email Server
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Admins to notify on 500 errors (via LOGGING's mail_admins handler below).
# Set ADMIN_EMAIL in the environment to enable; empty by default (no-op).
ADMIN_EMAIL = config('ADMIN_EMAIL', default='')
ADMINS = [('NexusAPI Admin', ADMIN_EMAIL)] if ADMIN_EMAIL else []


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost', cast=Csv())

CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:5173', cast=Csv())


# Security settings (only active when DEBUG=False)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False        # Nginx handles redirects, not Django
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000            # Set to 31536000 after SSL is confirmed working
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False


# Logging
APP_LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'AdminModule': {
            'handlers': ['console'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
        'FacultyModule': {
            'handlers': ['console'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
        'StudentModule': {
            'handlers': ['console'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
        'Models': {
            'handlers': ['console'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
    },
}


# Sentry — real-time exception alerting. No-op unless SENTRY_DSN is set.
SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=config('SENTRY_ENVIRONMENT', default='development'),
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            # our own LOGGING config already filters what reaches ERROR level;
            # mirror ERROR+ logs into Sentry as events, WARNING+ as breadcrumbs.
            LoggingIntegration(level=None, event_level='ERROR'),
        ],
        send_default_pii=False,
    )
